manager/manager/urls.py
from django.contrib import admin
from django.urls import path, include

from omnetppManager import views as omnetppManager_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('omnetppManager/', include("omnetppManager.urls")),
    path('', omnetppManager_views.redirect_to_here),

]

manager/omnetppManager/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import views as auth_views
from .decorators import already_authenticated, auth_required

from . import views

from .forms import getOmnetppiniForm, selectSimulationForm,getOmnetppBenchmarkSection,selectForwarderForm, BenchmarkGeneralSettingForm,UserEditorForm, ModelPredictionForm

from .views import NewSimWizard, JobDetailView, DetailSimWizard, BenchSimWizard

urlpatterns = [
        path('', views.index, name="omnetppManager_index"),
        path('queue_status/', views.queue_status, name="omnetppManager_queue_status"),
        path('job_status/', views.job_status, name="omnetppManager_job_status"),
        path('new-simulation/', auth_required(NewSimWizard.as_view([getOmnetppiniForm, selectSimulationForm, ModelPredictionForm])), name="omnetppManager_new-simulation"),
        path('manage_queues/', views.manage_queues, name="omnetppManager_manage_queues"),
        path('manage_queues/<output_format>/', views.manage_queues, name="omnetppManager_manage_queues"),
        path('job-details/<int:pk>/', auth_required(JobDetailView.as_view()), name='job-details'),
        path('job-kill/<int:pk>/', views.job_kill, name='job-kill'),
        path('newsim-detail/', auth_required(DetailSimWizard.as_view()), name="omnetppManager_detail_sim"),
        path('get-server-config/', views.get_server_config, name="omnetppManager_get_server_config"),
        path('get-simulation-details/',views.get_simulation_details, name="omnetppManager_get_simulation_details"),
        path('get-server-resources/',views.get_server_resources, name="omnetppManager_get_server_resources"),
        path('export-simulation-stats/', views.export_simulation_stats, name="omnetppManager_export_simulation_stats"),
        path('request-access/', views.request_access, name="omnetppManager_request_access"),
        path('request-access-thanks/', views.request_access_thanks, name="omnetppManager_request_access_thanks"),
        path('register/', views.register_users, name="omnetppManager_register"),
        path('login/', views.login_users, name="omnetppManager_login"),
        path('logout/', views.logout_users, name="omnetppManager_logout"),
        path('change-password/', views.change_password, name="omnetppManager_change_password"),
        path('activate/<uidb64>/<token>/', views.activate_account, name='activate_account'),
        path('resend-activation/', views.resend_activation, name='resend_activation'),
        path('reset-password/', already_authenticated(views.ResetPassword.as_view()), name="omnetppManager_reset_password"),
        path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
                success_url = reverse_lazy('omnetppManager_password_reset_complete')),name='omnetppManager_password_reset_confirm'),
        path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
                name='omnetppManager_password_reset_complete'),
        path('rerun-sim/<int:pk>', views.rerun_simulation, name="omnetppManager_rerun_sim"),
        path('benchmark-simulation/', auth_required(BenchSimWizard.as_view([getOmnetppBenchmarkSection, selectForwarderForm,UserEditorForm,BenchmarkGeneralSettingForm,])), name="omnetppManager_benchmark-simulation"),
        path('get-profile-parameter/', views.get_profile_parameters, name="omnetppManager_get_profile_parameters"),
        ]


## Currently used URLs
# status: show status of the queues
# new-simulation: create a new simulation
# manage_queues: get all data from the queues (after simulation finished)
# benchmark-simulation: create a new benchmark simulation

manager/omnetppManager/models.py
from django.conf import settings

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from django.core.exceptions import ValidationError

from django.core.validators import RegexValidator

from django.core.serializers.json import DjangoJSONEncoder

from django.db.utils import OperationalError

import uuid
import json

import datetime
from django.contrib.auth.models import Group, User



alphanumeric = RegexValidator(r'^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.')

# Create your models here.

## Model to store data storages
#
# Contains the data storage locations
#
class StorageBackend(models.Model):
    backend_name = models.CharField(max_length=100)
    backend_description = models.TextField(default="", help_text="Human-readable description of the field")
    backend_identifier = models.CharField(max_length=100, default="dropbox", help_text="identifier for the storage backend. Should only be used once")
    backend_token = models.CharField(max_length=100, null=True, blank=True, default=None, help_text="Token (if required)")
    backend_config = models.JSONField(default=str, null=True, blank=True, help_text="Additional information as a json object")
    backend_active = models.BooleanField(default=False)
    backend_keep_days = models.PositiveIntegerField(default=7)

    def __str__(self):
        label = str(self.backend_name)
        if self.backend_active:
            label += " (active)"
        return str(label)

## User predefined simulations (templates)
#
# Contains omnetpp.ini files
#
class SimOmnetppTemplate(models.Model):
    template_name = models.CharField(max_length=100)
    template_description = models.TextField(default="")
    template = models.TextField()
    template_active = models.BooleanField(default=False)

    def __str__(self):
        label = str(self.template_name)
        if self.template_active:
            label += " (active)"
        return str(label)



## Model to store Simulation details
#
# Stores the following data
# - user        : Reference to user who started the simulation
# - title       : Meaningful name of the simulation
# - omnetppini  : The omnetppini as a long text
# - runconfig   : Name of the config from the omnetpp.ini file
# - simulationid: The id given by the queue
class Simulation(models.Model):
    class Meta:
        ordering = ["-pk",]

    class Status(models.IntegerChoices):
        QUEUED      = 1, _("queued")
        FINISHED    = 2, _("finished")
        FAILED      = 3, _("failed")
        STARTED     = 4, _("started")
        DEFERRED    = 5, _("deferred")
        SCHEDULED   = 6, _("scheduled")
        UNKNOWN     = 7, _("unknown")
        ABORTED     = 8, _("aborted")

    class TerminateReason(models.IntegerChoices):
        NOT_TERMINATED      = 1, _("Simulation not terminated")
        TERMINATED_USER     = 2, _("Terminated by user")
        TERMINATED_EVENTS   = 3, _("Terminated by system: Exceeded events.")
        TERMINATED_CPU      = 4, _("Terminated by system: Exceeded CPU.")
        TERMINATED_RAM      = 5, _("Terminated by system: Exceeded RAM.")
        TERMINATED_DISK     = 6, _("Terminated by system: Exceeded Disk space.")


    user = models.ForeignKey(
            settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE,
            )
    title           = models.CharField(max_length=100)
    omnetppini      = models.TextField()
    runconfig       = models.CharField(max_length=100)
    summarizing_precision = models.FloatField(default=100)
    simulation_id   = models.UUIDField(
            editable=False,
            default = uuid.uuid4
            )
    status = models.IntegerField(choices=Status.choices, default=Status.UNKNOWN)

    terminated = models.IntegerField(choices = TerminateReason.choices, default = TerminateReason.NOT_TERMINATED)

    simulation_error = models.TextField(default=None, blank=True, null=True)

    job_error = models.TextField(default=None, blank=True, null=True)

    handled_by = models.CharField(max_length=100, default=None, blank=True, null=True)

    notification_mail_address = models.EmailField(default=None, blank=True, null=True)

    storage_backend = models.ForeignKey(StorageBackend, on_delete=models.SET_NULL, null=True, default=None)

    shared_link = models.CharField(max_length=250, default="")

    meta_full = models.TextField(default=None, blank=True, null=True)

    simulation_timeout = models.IntegerField(default=0)

    simulation_enqueue_time = models.DateTimeField(auto_now_add=True)

    simulation_start_time = models.DateTimeField(null=True, default=None)

    simulation_last_update_time = models.DateTimeField(null=True, default=None)

    simulation_state_times = models.TextField(default=None, blank=True, null=True)

    simulation_is_debug_sim = models.BooleanField(
            default=False,
            help_text="Is this a debug simulation? If yes -> ignore for comparison.",
            )
    sim_server = models.CharField(max_length=250, default="")
    
    Predicted_DiskSpace = models.FloatField(default=0)
    Predicted_RAM_Sim = models.FloatField(default=0)
    Predicted_RAM_Res = models.FloatField(default=0)
    Predicted_Time = models.FloatField(default=0)


    # String representation, mainly for debugging and admin model
    def __str__(self):
        return "Simulation " + str(self.simulation_id) + " started by user " + str(self.user)

    # Return url for detail view
    def get_absolute_url(self):
        return reverse('job-details', kwargs={
            'pk' : self.pk
            })

    ## Has shared link
    def get_shared_link(self):
        if self.shared_link and self.shared_link != "":
            return self.shared_link
        return None

    # Return the meta data in a proper way for the template processing
    def get_meta(self):
        if self.meta_full:
            try:
                # json object?
                return json.loads(self.meta_full)
            except:
                try:
                    # non json object? # TODO: rm eval
                    return eval(self.meta_full)
                except:
                    pass
        return None


    # Access the scalar stats
    def get_scalar_stats(self, statname):
        meta = self.get_meta()
        if not "scalar_stats" in meta:
            return None

        for s in meta["scalar_stats"]:
            if statname == s[0]:
                return s[-1]

        print("key not found")
        return None

    # Access the simulation runtime stats
    def get_sim_runtime_stats(self, statname):
        meta = self.get_meta()

        if not "sim_runtime_stats" in meta:
            return None
        for s in meta["sim_runtime_stats"]:
            # print(s)
            if statname == s[0]:
                # print(s, s[1])
                return s[1]
        return None

    # Access to the total number of events for the template
    def get_total_events(self):
        return self.get_sim_runtime_stats("totevents")

    # Access simulation runtime
    def get_sim_runtime(self):
        meta = self.get_meta()

        if self.status == 8 or self.status == 3:
            update_time = self.simulation_last_update_time
            update_time = int(update_time.strftime('%s'))
            start_time = self.simulation_start_time
            start_time = int(start_time.strftime('%s'))
            sim_time = update_time - start_time
            sim_time =  "{}".format(str(datetime.timedelta(seconds=sim_time)))
        elif "sim_run_time" in meta and meta["sim_completed_perc"] == 100:
            end_time = int(meta["sim_run_time"])
            start_time = self.simulation_start_time
            start_time = int(start_time.strftime('%s'))
            sim_time = end_time - start_time
            sim_time = "{}".format(str(datetime.timedelta(seconds=sim_time)))
        elif meta["current_state"] == 'SIMULATING' and self.status != 8 and self.status != 3 and "sim_time_sofar" in meta:
            sim_time = int(meta["sim_time_sofar"])
            sim_time = "{}".format(str(datetime.timedelta(seconds=sim_time)))
        else:
            sim_time = ''
    
        return sim_time

    ## Notify user on sim state change
    def send_notify_mail(self):
        return self.notification_mail_address not in ["", None]

    ## status for template rendering: queued
    def is_queued(self):
        return self.status == self.Status.QUEUED

    ## status for template rendering: finished
    def is_finished(self):
        return self.status == self.Status.FINISHED

    ## status for template rendering: failed
    def is_failed(self):
        return self.status == self.Status.FAILED

    ## status for template rendering: started
    def is_started(self):
        return self.status == self.Status.STARTED

    ## status for template rendering: deferred
    def is_deferred(self):
        return self.status == self.Status.DEFERRED

    ## status for template rendering: scheduled
    def is_scheduled(self):
        return self.status == self.Status.SCHEDULED

    ## status for template rendering: aborted
    def is_aborted(self):
        return self.status == self.Status.ABORTED

    ## Calculate simulation timeout
    def get_timeout(self):
        return self.simulation_enqueue_time +\
                datetime.timedelta(seconds=self.simulation_timeout)

    ## Return formatted timeout
    def get_simulation_timeout_formatted(self):
        return str(datetime.timedelta(seconds=self.simulation_timeout))

    ## Return the times when a state changed
    def get_state_times(self):
        times = self.simulation_state_times
        if times:
            return json.loads(self.simulation_state_times)
        else:
            return {}

    ## Add new state change event
    def add_state_times(self, state, time):
        times = self.simulation_state_times
        newTimes = {}
        if times:
            newTimes = json.loads(times)

manager/omnetppManager/templates/omnetppManager/bench_simulation.html
{% extends "base_generic.html" %}

{% block content %}

<h2 class="display-3">Start a new benchmark simulation</h2>
<h5> Step {{ wizard.steps.step1 }} of {{wizard.steps.count}} of simulation <code>{{ simulation_title }}</code></h5>
{% if wizard.steps.step1 == 3%}
  <h5>You have selected  {{simulation_name}}  and {{forwarding_layer}} layer</h5><br>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ wizard.management_form }}
    <table>

    {% if wizard.form.forms %}
      {{ wizard.form.management_form }}
          {% for form in wizard.form.forms %}
            {{ form }}
          {% endfor %}
        {% else %}
          {% if wizard.steps.step1 == 3%}
          <h4>Edit RNG parameters below</h4><br>
          <div class="row rngs">
          {% for field in form %}
          {% if forloop.counter == 7 %}
          <div class="col-lg-12 col-md-12 col-xs-12 ">
            <h4 id="forward_tag"> Edit Forwarding layer parameters below</h4><br>
          </div>
          {% endif %}
          {% if 'form-control rng' in field.field.widget.attrs.class %}
          <div class="col-lg-5 col-md-5 col-xs-12  rng">
            <div class="col-lg-12 col-md-12 col-xs-12 form-inline">
              <label id="rng_label" for="{{ field.auto_id }}">{{ field.label }}</label>
              {{ field }} 
            </div>
            <div class="col-lg-12 col-md-12 col-xs-12">
              <em>{{ field.help_text }}</em>
              {% if field.errors %}
                {% for error in field.errors %}
                <p class="rng_error">
                    <strong>{{ error|escape }}</strong>
                </p>
                {% endfor %}
              {% endif %}
            </div>
          </div>
          {% else %}
          <div class="container">
          <div class="col-lg-7 col-md-7 col-xs-12 forward_sections">
            <label id="rng_label" for="{{ field.auto_id }}">{{ field.label }}</label>
             {{ field }}
            {{ field.help_text }}
            {% if field.errors %}
                {% for error in field.errors %}
                <p class="rng_error">
                    <strong>{{ error|escape }}</strong>
                </p>
                {% endfor %}
              {% endif %}
            <br>
          </div>
          </div>
          {% endif %}
          {% endfor %}
        </div>
        {% else %}
          {{ wizard.form }}
          {% endif %}
        {% endif %}

    </table><br>
    <input type="submit" name="wizard_goto_step" value="next"/>
    <br> <br>
</form>

{% endblock %}

manager/omnetppManager/templates/omnetppManager/create_detail_sim.html
{% extends "base_generic.html" %}
{% load static %}

{% block head %}
<script src="{% static 'js/tools.js' %}"></script>
{% endblock %}


{% block content %}

<h1 class="display-3">Start a new simulation</h1>
<form class="form-horizontal" method="POST" action="">
{% csrf_token %}
{{wizard.management_form}}

{% if wizard.form.forms %}
    {{ wizard.form.management_form }}

    {% if form.non_form_errors %}
    <span class="error text-danger">
        {% for error in form.non_form_errors %}
        {{ error }}
        {% endfor %}
    </span>
    {% endif %}

<table class="table">
    {% for form in wizard.form.forms %}

        {{form.non_field_errors}}

        {% if forloop.first %}
        <thead>
            <tr>
        {% for field in form %}
        <th scope="col">{{field.label}}</th>
        {% endfor %}

            <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        {% endif %}

            <tr>
        {% for field in form %}
        <td>
                {{field}}
                {% if field.errors %}
                <span class="error text-danger">
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                </span>
                {% endif %}
        </td>
            {% if forloop.last %}
                {% if forloop.parentloop.last %}
                <td><button class="btn btn-success add-form-row">+</button></td>
                {% else %}
                <td><button class="btn btn-danger remove-form-row">-</button></td>
                {% endif %}
            {% endif %}
        {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
        </table>

{% else %}
{{wizard.form}}
{% endif %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-auto">
step {{ wizard.steps.step1 }} from {{ wizard.steps.count }}
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            <div class="btn-group" role="group" aria-label="Navigation">
            {% if wizard.steps.prev %}
            <button class="btn btn-primary" type="submit" value="{{ wizard.steps.first }}">first step</button>
            <button class="btn btn-primary" type="submit" value="{{ wizard.steps.prev }}">prev step</button>
            {% endif %}
            <button type="submit" class="btn  btn-primary">Continue</button>

            </div>

        </div>
    </div>

</div>

</form>

    <script>
        initEventListeners();
    </script>
{% endblock %}

manager/omnetppManager/templates/omnetppManager/index.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="display-3">OMNeT++ Simulation Testserver</h1>

<p>Tired of setting up simulation? ootb aims on easy to setup simulation. The following video gives a brief introduction to the main functions of OOTB.</p>

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/4GDNheit1qc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    {% for message in messages  %}
    <script>
    alert('{{ message }}')
    </script>
    {% endfor %}

{% endblock %}

manager/omnetppManager/templates/omnetppManager/job_status_page.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="display-3">Simulation Status</h1>

<div class="d-flex justify-content-center">
        {% if jobs.has_previous %}
            <div class="px-2"><a href="?page=1">&laquo; First page</a></div>
            <div class="px-2"><a href="?page={{ jobs.previous_page_number }}">back</a></div>
        {% endif %}

            Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}

        {% if jobs.has_next %}
            <div class="px-2"><a href="?page={{ jobs.next_page_number }}">next</a></div>
            <div class="px-2"><a href="?page={{ jobs.paginator.num_pages }}">last page &raquo;</a></div>
        {% endif %}
</div>


<table class="table">
    <thead>
        <tr>
        <th scope="col">job id</th>
        <th scope="col">title</th>
        <th scope="col">run config</th>
        <th scope="col">started by</th>
        <th scope="col">status</th>
        <th scope="col">action</th>
        </tr>
    </thead>
    <tbody>
        {% for job in jobs %}
        <tr>
            <td><a href="{{ job.get_absolute_url }}">{{job.simulation_id}}</a></td>
            <td>{{job.title}}</td>
            <td>{{job.runconfig}}</td>
            <td>{{job.user}}</td>
            <td class="{% if job.is_finished %}bg-success{% elif job.is_failed %}bg-danger{% elif job.is_started %}bg-primary{% elif job.is_aborted %}bg-warning{% elif job.is_queued %}bg-warning{% endif %}">{{job.get_status_display}}</td>
            <td>
                <form action="{% url 'job-kill' pk=job.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" aria-label="Kill Simulation">
                        <i class="fa fa-times" aria-hidden="true"></i>
                    </button>
                </form>
                <a href="{% url 'omnetppManager_rerun_sim' pk=job.id %}" class="btn btn-primary" aria-label="Restart Simulation">
                    <i class="fa fa-repeat" aria-hidden="true"></i>
                </a>

            </td>

        </tr>
        {% endfor %}

    </tbody>

</table>

<div class="d-flex justify-content-center">
        {% if jobs.has_previous %}
            <div class="px-2"><a href="?page=1">&laquo; First page</a></div>
            <div class="px-2"><a href="?page={{ jobs.previous_page_number }}">back</a></div>
        {% endif %}

            Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}

        {% if jobs.has_next %}
            <div class="px-2"><a href="?page={{ jobs.next_page_number }}">next</a></div>
            <div class="px-2"><a href="?page={{ jobs.paginator.num_pages }}">last page &raquo;</a></div>
        {% endif %}
</div>


{% endblock %}

manager/omnetppManager/templates/omnetppManager/manage_queues.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="display-3">Queue management done</h1>
<p>Got {{ finished_jobs }} finished and {{failed_jobs}} failed jobs. Updated status of {{updated_jobs}} jobs.</p>
{% endblock %}

manager/omnetppManager/templates/omnetppManager/queue_status_page.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="display-3">Status Summary</h1>


<table class="table">
	<thead>
		<tr>
		<th scope="col">job status</th>
		<th scope="col">number</th>
		</tr>
	</thead>
	<tbody>
		{% for status in status %}
		<tr>
			<td>{{status.name}}</td>
			<td>{{status.number}}</td>

		</tr>
		{% endfor %}

	</tbody>

</table>

{% endblock %}

manager/omnetppManager/templates/omnetppManager/request_access.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="display-3">Demo Account Request</h1>
<p>Our <i>Ops On The Bench</i> (OOTB) simulation service is currently in a closed beta test. Using this form, you can request a demo account.</p>

<form action="{% url 'omnetppManager_request_access' %}" method="post">
    {% csrf_token %}

    {% if form.non_form_errors %}
    <span class="error text-danger">
        {% for error in form.non_form_errors %}
        {{ error }}
        {% endfor %}
    </span>
    {% endif %}


    <table class="table">
        <tbody>
        {% for field in form %}
        <tr>
            <td>{{field.label}}</td><td>{{field}} <small class="form-text text-muted">{{field.help_text}}</small></td>

        </tr>

        {% endfor %}
        </tbody>
    </table>
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}

manager/omnetppManager/templates/omnetppManager/request_access_thanks.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="display-3">Request sent</h1>
<p>Thank you for your request. We will come back to you shortly.</p>
{% endblock %}

manager/omnetppManager/templates/omnetppManager/simulation_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1 class="display-3">Simulation details for &quot;{{object.title}}&quot;</h1>

<ul>
    <li>Title: {{object.title}}</li>
    <li>User: {{object.user}}</li>
    <li>Run config: {{object.runconfig}}</li>
    <li>Status: <code>{{object.get_status_display}}</code></li>
    <li>Terminated: <code>{{object.get_terminated_display}}</code></li>
    <li>Precision: {{object.summarizing_precision}} s</li>
    <li>ID: <code>{{object.simulation_id}}</code></li>
    <li>Storage backend: {{object.storage_backend.backend_name}}</li>
    <li>Timeout: {{ object.get_simulation_timeout_formatted }}</li>
    <li>Will timeout: {{ object.get_timeout }} (UTC)</li>
    {% if object.send_notify_mail%}
    <li>Last status change: {{object.simulation_last_update_time}}</li>
    <li>All status changes: <code>{{object.get_state_times}}</code></li>
    <li>Notifications to {{object.notification_mail_address}}</li>
    {% else %}
    <li>No notifications enabled</li>
    {% endif %}
    {% if object.handled_by %}
    <li>Simulation server: {{ object.handled_by }}</li>
    {% endif %}
    {% if object.shared_link %}
    <li><a href="{{object.shared_link}}" target="_blank">Download results</a></li>
    {% endif %}
</ul>

{% if object.meta_full %}
<h2 class="display-5">Simulation Meta Data</h2>
<ul>
    <li>
        <label for="sim_percentage">
            Simulation Percentage: {{ object.get_meta.sim_completed_perc }}&percnt;
        </label>
        <progress id="sim_percentage" value="{{ object.get_meta.sim_completed_perc }}" max="100">
            {{ object.get_meta.sim_completed_perc }}&percnt;
        </progress>
    </li>
    <li>
        <label for="res_percentage">
            Result Processing Percentage: {{ object.get_meta.results_completed_perc }}&percnt;
        </label>
        <progress id="res_percentage" value="{{ object.get_meta.results_completed_perc }}" max="100">
            {{ object.get_meta.results_completed_perc }}&percnt;
        </progress>
    </li>

    <li>Current state: <code>{{ object.get_meta.current_state }}</code></li>
    <li>Simulation start time: {{ object.get_meta.start_time_str }}</li>
    <li>Total simulation time so far: {{ object.get_sim_runtime }}</li>

    <li>Resource usage:
        <ul>
            <li>Simulation: Peak RAM usage: {{ object.get_meta.peak_sim_ram_usage|filesizeformat }}</li>
            <li>Results: Peak RAM usage: {{ object.get_meta.peak_results_ram_usage|filesizeformat }}</li>
            <li>Peak disk usage: {{ object.get_meta.peak_disk_usage|filesizeformat }}</li>
            {% if object.get_total_events %}
                <li>Total number of events: {{object.get_total_events}}</li>
            {% endif %}
        </ul>
    </li>


</ul>
{% endif %}

<h2 class="display-5">omnetpp.ini</h2>
<p>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseCode" aria-expanded="false" aria-controls="collapseCode">
      Show / hide omnetpp.ini
  </button>
</p>
<div class="collapse" id="collapseCode">
    <code>
        {{object.omnetppini|linebreaks|safe}}
    </code>
</div>

{% if object.meta_full %}

<h2 class="display-5">Raw meta data</h2>
<p>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseMeta" aria-expanded="false" aria-controls="collapseMeta">
      Show / hide full meta data
  </button>
</p>
<div class="collapse" id="collapseMeta">
    <code>
        {{object.meta_full|linebreaks|safe}}
    </code>
</div>



{% endif %}

{% if object.simulation_error%}

<h2 class="display-5">Simulation error</h2>
<code>
    {{object.simulation_error|linebreaks|safe}}
</code>
{% endif %}

{% if object.job_error%}

<h2 class="display-5">Job execution error</h2>
<code>
    {{object.job_error|linebreaks|safe}}
</code>
{% endif %}


{% endblock %}